apiVersion: apps/v1
kind: Deployment
metadata:
  name: nono-octopus-nginx:1.27.5
  namespace: not-octopus-argo # Ensure this matches the Argo CD app's destination namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx:1.27.5
  template:
    metadata:
      labels:
        app: my-nginx:1.27.5
    spec:
      containers:
      - name: nginx:1.27.5-container
        image:  nginx:1.27.5
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx:1.27.5/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx:1.27.5-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx:1.27.5-service
  namespace: not-octopus-argo # Ensure this matches the Argo CD app's destination namespace
spec:
  selector:
    app: my-nginx:1.27.5
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30069
  type: NodePort # Or ClusterIP if you don't need external access
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx:1.27.5-configmap
  namespace: not-octopus-argo # Ensure this matches the Argo CD app's destination namespace
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello from Nginx!</title>
    </head>
    <body>
      <h1>Go away Octopus, you're not welcome here.</h1>
    </body>
    </html>
